### ISSUE TITLE
prevents copying text from the page...

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#1]
0.10.6.3 (FF + Cent)

Noticed that after downloading something from a page (even just an archive, not necessarily a media file), the **ability to copy text disappears** on it. That is, when pasting into a text editor, not what is copied appears, but the previous text from the buffer. It's as if the text on the page becomes "copy-protected". Only disabling the mod and page refresh helps.

Try, for example, to go here, download any FB2 archive, and then copy some text:
http://flibusta.is/sequence/79139

**Comment by TheFantasticWarrior** [comment]
Should be fixed in 10.6.4, do we discuss future problems here? Or continue on Reddit? I'm fine with both.

**Comment by kuzn123** [comment]
Everything is working now, thank you.

> do we discuss future problems here? Or continue on Reddit?

I would like to move the discussion of technical issues (and problems) of your mod here. 

But there are users on Reddit who are not registered on Github, so they will also have to answer some questions there. Perhaps I will delete the old topic altogether and create a new one, since the name cannot be edited on Reddit, and it is already misleading (as if the mod is only for FF).
