### ISSUE TITLE
Chrome shortcut issues

### ISSUE THREAD

**Issue by 54m4d** [TheFantasticWarrior/chrome-extension-imagus#12]
Hello

On Chrome latest version, "Click to open options page" and "Shift click to toggle on/off" don't work, on FF they work but not on Chrome, nothing happens when i click or shift click, is this a bug?

**Comment by TheFantasticWarrior** [comment]
For chrome please use the previous version, for some reason the new code only works in Firefox

**Comment by 54m4d** [comment]
Which one? Today i'm using https://github.com/TheFantasticWarrior/chrome-extension-imagus/commit/e6bd6efb46ac2fb89744ed5d1b55e601eff47b92

**Comment by TheFantasticWarrior** [comment]
In 0.10.9.1 it should work now, the only version that it doesn't work is 0.10.9

**Comment by 54m4d** [comment]
It's working now, but how to toggle on/off on Chrome?

**Comment by TheFantasticWarrior** [comment]
Currently chrome only supports normal clicking the icon so you need to use the hotkey
