### ISSUE TITLE
Permission issue in Waterfox Classic

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#13]
In the Waterfox Classic 2022.11, the dialog for granting the **permission to download files** just does not appear... Accordingly, downloading content by hotkey does not work in this browser.

**Comment by TheFantasticWarrior** [comment]
Waterfox (102.11.0) no issue

**Comment by kuzn123** [comment]
> Waterfox (102.11.0) no issue

I mean exactly Waterfox Classic. But maybe it just can't be done there, it's based on the old "engine"...
