### ISSUE TITLE
Renaming the sieves broken on FF

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#14]
SHIFT+RIGHT CLICK - just a normal RIGHT CLICK.

At the same time, renaming works fine on Chromium browsers. Perhaps it has something to do with using SHIFT+CLICK on the extension icon to access the Settings in FF?

**Comment by TheFantasticWarrior** [comment]
sorry for late reply, it is caused by firefox feature https://bugzilla.mozilla.org/show_bug.cgi?id=897379, mind if I change it to normal right click?

**Comment by kuzn123** [comment]
> mind if I change it to normal right click?

If you mean renaming sieves, then it would probably be even better. The standard context menu is not needed there.

**Comment by TheFantasticWarrior** [comment]
should be fixed https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.10

**Comment by kuzn123** [comment]
Thanks, it works.
