### ISSUE TITLE
PgDn does not react with the pre -view

### ISSUE THREAD

**Issue by PhoenixIndigo** [TheFantasticWarrior/chrome-extension-imagus#16]
PgDn does not respond with a pre -detention, & Down, PageDown, Space reacts + wheel.

**Comment by kuzn123** [comment]
Nothing is clear from your message.

**Comment by PhoenixIndigo** [comment]
Кнопка 3)PgDn не работает и не отвечает, когда просматриваешь предпросмотр Imagus.
The 3)PgDn button does not work and does not answer when you view the preview. Imagus.

**Comment by kuzn123** [comment]
А PgDn точно должен там работать? Какая функция горячей клавиши имеется в виду (на вкладке "Сочетания клавиш")?

У меня навигация по всплывашке Имагуса настроена по другому - активация всплывашки щелчком мыши (ПКМ) и далее перемещение по ней движением курсора, а увеличение/уменьшение нужного фрагмента картинки/видео - колесом мыши.

**Comment by PhoenixIndigo** [comment]
Во первых объясните про длинное нажатие правой кнопкой, а то непонятно как ей увеличивать в Firefox 112, а то она открывает только меню, что и необходимо.
А во вторых 3)`PgDn` не опускает страницу вниз:
<details><summary>Details</summary>
<p>

![](https://user-images.githubusercontent.com/107413021/236293903-5e1a7b31-d689-4661-a9bf-79066171bc12.png)
![](https://user-images.githubusercontent.com/107413021/236292414-e3afd5ea-0d27-4ce9-8538-e14e37cfd4dc.png)

</p>
</details>

**Comment by PhoenixIndigo** [comment]
А да 2)`Down` & 1)`End` тоже не пашут по назначению.

**Comment by kuzn123** [comment]
>Во первых объясните про длинное нажатие правой кнопкой

https://i.imgur.com/hngqNgU.png

>PgDn не опускает страницу вниз

Где конкретно?

**Comment by PhoenixIndigo** [comment]
Ну длительное точно не пашет.
Здесь тоже!

**Comment by PhoenixIndigo** [comment]
https://addons.mozilla.org/ru/firefox/collections/17366156/My-extensions/?page=1&collection_sort=name

**Comment by kuzn123** [comment]
> Ну длительное точно не пашет.
> Здесь тоже! [Дополнения](https://addons.mozilla.org/ru/firefox/collections/17366156/My-extensions/?page=1&collection_sort=name)

А причем тут Имагус? Это у вас что-то с браузером. На моем FF DE 113 все клавиши (PgDn, End) на этой странице работают.

**Comment by PhoenixIndigo** [comment]
У меня и на английском и на чистом профиле также. Win 10x64

**Comment by PhoenixIndigo** [comment]
У меня и на английском и на чистом профиле также. Win 10x64. У меня и хроме также, и это вы за зря так думаете, не удобно.
Я про совмещённые переключаемые клавиши а не про одиночки!

**Comment by kuzn123** [comment]
> Я про совмещённые переключаемые клавиши а не про одиночки!

Ни "совмещенные", ни одиночные клавиши не работают во всплывающем окне Имагус. И не должны работать. Работает только навигация курсором - движением или перетаскиванием (в опциях можно выбрать на выбор, я рекомендую движением).

**Comment by PhoenixIndigo** [comment]
У меня и хроме также, и это вы за зря та думаете, не удобно.

**Comment by PhoenixIndigo** [comment]
У меня и хроме также, и это вы за зря так думаете, не удобно.
Настройте по умолчанию без увеличения и подтвердится это.

**Comment by kuzn123** [comment]
> У меня и хроме также, и это вы за зря так думаете, не удобно.
> Настройте по умолчанию без увеличения и подтвердится это.

Еще раз: без понятия что и где у вас не работает, но нет никаких признаков, что это имеет отношение к Имагус. Соответственно, заканчиваем этот бессмысленный разговор.

**Comment by PhoenixIndigo** [comment]
Блин да вы чё вы такой не врубчивый. Я же объяснил какие [**_дополнительные_**](https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-magic-acc-202203?wid=400&hei=500&fmt=p-jpg&qlt=95&.v=1645055994661) клавиши что справа от других таких не отвечают при предварительном предпросмотре не увеличивая курсором с имагус ссылок на картинки!

**Comment by PhoenixIndigo** [comment]
[**_Вы что совсем не знакомы с расширенной клавиатурой Уиндоус???_**](https://avatars.mds.yandex.net/get-mpic/4220209/img_id8293817517745044649.jpeg/orig)

**Comment by PhoenixIndigo** [comment]
https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-magic-acc-202203?wid=400&hei=500&fmt=p-jpg&qlt=95&.v=1645055994661

**Comment by PhoenixIndigo** [comment]
https://club.dns-shop.ru/api/v1/image/getOriginal/28edce8ba4f4462d18888c898314f793ccc899c40db8acacd35138ae8807f96a.jpg/
https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-magic-acc-202203?wid=400&hei=500&fmt=p-jpg&qlt=95&.v=1645055994661

**Comment by PhoenixIndigo** [comment]
https://avatars.mds.yandex.net/get-mpic/4220209/img_id8293817517745044649.jpeg/orig
<details><summary>-X-</summary>
<p>

![](https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-card-40-magic-acc-202203?wid=400&hei=500&fmt=p-jpg&qlt=95&.v=1645055994661)

</p>
</details>

**Comment by PhoenixIndigo** [comment]
Да у меня даже и при зуме та же ерунда! **Вы что совсем с крыши съездились**?

**Comment by PhoenixIndigo** [comment]
**Из-за вашего даунства страдают Уиндоус юзеры!!!**
