### ISSUE TITLE
The right buttons from below do not answer

### ISSUE THREAD

**Issue by PhoenixIndigo** [TheFantasticWarrior/chrome-extension-imagus#17]
А зачем зафиксировали тему #16? Разве вам не нужно чужое подтверждение проблемы, которая прямо относится к имагус и не является офф-топом?

А то что у вас не реагируют это ваш косяк. Плюс длинное правое нажатие тоже не работает!
<details><summary>Details</summary>
<p>

![Клавиши](https://avatars.mds.yandex.net/get-mpic/4220209/img_id8293817517745044649.jpeg/orig)
![Мышь](https://c.dns-shop.ru/thumb/st1/fit/wm/0/0/1a8ccf53d30f8a7a97edceeeb8b6fa97/c1b3c7d7fbb3d37773e698751f0b7090bff2375cc1a057d1247c6c7cec3242f4.jpg)

</p>
</details>

**Comment by kuzn123** [comment]
Еще раз: ваши сообщения являются оффтопом, потому что ни о какой поддержке "дополнительных клавиш" или дополнительных клавиш на мышке и т.п. в Имагус даже речи нет. Кроме того, из ваших сообщений почти ничего не понятно, это какой-то поток сознания, разгребать который лично у меня нет ни времени, ни желания.

Единственное, что я могу еще сделать - на какое-то время оставить этот топик открытым для обсуждения, если автор захочет разобраться в чем там у вас проблема. Если он вам не ответит, то этот ваш топик также будет закрыт.

**Comment by PhoenixIndigo** [comment]
<details><summary>Details</summary>
<p>

![Клавиши](https://avatars.mds.yandex.net/get-mpic/4220209/img_id8293817517745044649.jpeg/orig)
![Мышь](https://c.dns-shop.ru/thumb/st1/fit/wm/0/0/1a8ccf53d30f8a7a97edceeeb8b6fa97/c1b3c7d7fbb3d37773e698751f0b7090bff2375cc1a057d1247c6c7cec3242f4.jpg)

</p>
</details>

**Comment by TheFantasticWarrior** [comment]
Sorry that I don't understand russian and is busy recently so couldn't respond, can you please use a translator so I can understand your problem better?

For long right click you need to hold then release. 

Album keys only work in albums, or in other words a popup with multiple images/videos
Or do you mean it's blocking input when it's not hovering over the album?

I hope you can understand my comment either by yourself or through translation

@kuzn123 please only delete or edit off topic parts, leave the actual discussions visible, and try to ask for more information if possible
if this is too much for you just answer parts you know, like things in the FAQ or simple questions

**Comment by PhoenixIndigo** [comment]
Yes, thanks, I translated your message.
The long right -clicking on the link causes only the context menu, and does not increase. And when viewing the imagus of views, as with an increase in and without, digital keys switched to actions on the page, 1) end; 2)) Down; 3) PGDN not blocked, and other keys: arrows, home; end; pageup; pageDown; 7) Home; 8) up; 9) PGUP work, like the mouse wheel without increasing.

**Comment by PhoenixIndigo** [comment]
Thanks, I translated your message.
The long righ -clicking on the link causes only the context menu, and does not increase. And when viewing the imagus of views, as with an increase in and without, digital buttons switched to actions on the page, 1) End; 2) Down; 3) PgDn blocked, and not blocked other buttons : Arrows; Home; End; PageUp; PageDown; 7) Home; 8) Up; 9) PgUp work, like the mouse wheel without increasing.
<details><summary>Details</summary>
<p>

![](https://user-images.githubusercontent.com/107413021/236617908-4351a4f8-ab0c-4e58-b36c-bb23f555da71.png)

</p>
</details>

**Comment by TheFantasticWarrior** [comment]
Извините, но мне трудно понять ваш английский. Не могли бы вы использовать Bing AI Translate, чтобы помочь нам лучше общаться?
переведено с помощью Bing:
I understand now. Теперь я понимаю.
![orig](https://user-images.githubusercontent.com/39485135/236619783-b3434fac-83ab-4d0b-bd0a-6aeba5feba73.png)
you want the numpad(blue) instead of the navigation keys(red) to work(easy)? Or do you want both to work(I have to change code)
Вы хотите, чтобы работал нумпад (синий), а не клавиши навигации (красные) (легко)? Или вы хотите, чтобы оба работали (мне нужно изменить код)?

Can you set the buttons in the settings and tell me what is the text? I think it will be number, like this
Можете ли вы настроить кнопки в настройках и сказать мне, какой текст? Я думаю, это будет число, например так
![2023-05-06 19-00-57](https://user-images.githubusercontent.com/39485135/236620302-9eb95efe-1095-493f-8edf-75bf2e348625.jpg)

for long right clicking it only full zoom after the zoom already happens, or does that also not work?
Для длительного правого щелчка он полностью увеличивается только после того, как увеличение уже произошло, или это тоже не работает?

**Comment by PhoenixIndigo** [comment]
> you want the numpad(blue) instead of the navigation keys(red) to work(easy)?

All

> Can you set the buttons in the settings and tell me what is the text? I think it will be number, like this

Work

> for long right clicking it only full zoom after the zoom already happens, or does that also not work?

It also does not work

**Comment by PhoenixIndigo** [comment]
> you want the numpad(blue) instead of the navigation keys(red) to work(easy)?

All

> Can you set the buttons in the settings and tell me what is the text? I think it will be number, like this

No

> for long right clicking it only full zoom after the zoom already happens, or does that also not work?

Does not work

**Comment by PhoenixIndigo** [comment]
>  you want the numpad(blue) instead of the navigation keys(red) to work(easy)? Or do you want both to work(I have to change code)

Yes, all

> Can you set the buttons in the settings and tell me what is the text? I think it will be number, like this

Does not work. Moreover, I can’t even return the default settings in the Firefox as to change back

> for long right clicking it only full zoom after the zoom already happens, or does that also not work?

Does not work

**Comment by TheFantasticWarrior** [comment]
After changing the repeated pageup/down(in video/audio), and numbers in middle to something else,
Use 2 of the 3 options to set both keys, for example
![2023-05-10 19-22-25](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/39485135/7cc0a6e6-2ffa-48cf-8ddf-391ec3511166)

Is it ok? I think other users might use numpad as numbers more

**Comment by PhoenixIndigo** [comment]
I have NUMPUD switches to the numbers about what the first light bulb shows.
I am disappointed, but I hope the settings will change themselves everywhere.
<details><summary>Details</summary>
<p>

![](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/107413021/b82440ed-44fa-4e3a-9fd6-1fbb762107bd)

</p>
</details>

**Comment by PhoenixIndigo** [comment]
I even have if you take 12346789, then the main navigation buttons become not free.

**Comment by TheFantasticWarrior** [comment]
try v0.10.11, if you're good with it close the issue
check this box
![2023-05-11 14-14-33](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/39485135/762e4db0-0824-4501-826b-e807e8eda956)

**Comment by PhoenixIndigo** [comment]
Thanks works in Chrome, I haven’t checked in the Firefox yet, so I’ll close the topic after checking the Firefox.

**Comment by PhoenixIndigo** [comment]
The moment does not work yet, the right long clicking with the mouse!

**Comment by TheFantasticWarrior** [comment]
> The moment does not work yet, the right long clicking with the mouse!

sorry I can't replicate the issue, does normal right click work?

**Comment by PhoenixIndigo** [comment]
Certainly

**Comment by PhoenixIndigo** [comment]
I was mistaken, both a click and a long press with the right mouse button, does not increase, but only opens the menu. Firefox

**Comment by PhoenixIndigo** [comment]
So you can make the right mouse button work, by click or long press, otherwise they will not work!
