### ISSUE TITLE
Unable to update Sieves.

### ISSUE THREAD

**Issue by 54m4d** [TheFantasticWarrior/chrome-extension-imagus#23]
Hello

Today i can't update the sieves, i deleted them all, but when i click the update button, it says Loading, but nothing happens after that.

<details>
<summary>Screen</summary>
<img src=https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/52612348/d0a5c94d-cdf8-47ca-842f-ee8ec005fcb3>
</details>

**Comment by TheFantasticWarrior** [comment]
Are there other things you did that created the issue? Does it still happen after reloading?

**Comment by 54m4d** [comment]
Yes, it happens after reloading, another thing i also noticed, yesterday imagus stopped working and when i tried to go to the settings, it was just blank, but when i restarted Chrome it worked normally again, never had this happen before, maybe there are some small bugs here and there.

**Comment by TheFantasticWarrior** [comment]
if the settings page is completely blank that means an error has occurred in the background script, can you screenshot the error in chrome://extensions page or is it gone after you restart chrome?

**Comment by 54m4d** [comment]
The extension setting stage was completely blank, it could be that an error has occurred in the background script indeed but I have not checked in the Chrome extensions page, but usually errors are not displayed there, do you maybe mean in the console? And yes after I restarted Chrome I could access the settings of imagus normally again.

**Comment by TheFantasticWarrior** [comment]
> but usually errors are not displayed there

it only does when the error is from background script 

>do you maybe mean in the console? 

accessing console of background script is different from normal console, and it gets cleared after restart, I thought maybe there's a chance that the extensions page does keep it after restart

>And yes after I restarted Chrome I could access the settings of imagus normally again.

does sieve update normally after you restart? In firefox it works normally, but I find that clicking save and updating again is sometimes necessary for chrome

**Comment by 54m4d** [comment]
No it does not.

OK, so i did another test and i found out that v0.10.11.1 does not have this issue at all, so it's clearly a conflict with the introduction of the new `~` function.

Maybe some more troubleshooting is needed.

**Comment by 54m4d** [comment]
Fixed with the new update url.
