### ISSUE TITLE
A serious bug in new versions on Chromium browsers

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#26]
A serious bug has been found In new versions on **Chrome/Chromium**, starting from version **0.10.11.1** (see my [message](https://www.reddit.com/r/imagus/comments/121oop7/comment/jpi0m4j)).

On **0.10.11** and FireFox, everything is fine.

**Comment by 54m4d** [comment]
They changed the xhr call from background script to the content script, which fixes cookie bugs on firefox(in incognito the cookie can be set/accessed by websites) but this also affects Chromium browsers https://bugzilla.mozilla.org/show_bug.cgi?id=1833842
They need to revert the change for Chrome and maintain 2 separate versions, one for Chromium and one for Gecko.

Duplicate/related #21 #25

**Comment by TheFantasticWarrior** [comment]
I separated the versions in v0.10.14, should work now

**Comment by kuzn123** [comment]
> I separated the versions in v0.10.14, should work now

Thank you, the bug has been fixed in this version. But why is there no version update for FF on the extension page? The latest version there is 0.10.11.

**Comment by TheFantasticWarrior** [comment]
Just want to make sure there are no bugs before official release
