### ISSUE TITLE
Ctrl+S saves html instead of image

### ISSUE THREAD

**Issue by ongots** [TheFantasticWarrior/chrome-extension-imagus#28]
I checked on several sites. Rolled back to the previous version.

**Comment by kuzn123** [comment]
On which sites exactly do you have this happening?

**Comment by ongots** [comment]
I checked again, at all (github, reddit, tumblr, google images). "Save as: html" window pops up

**Comment by TheFantasticWarrior** [comment]
Does imagus mod have the permission to download?
Have you reloaded the page after installing/updating the extension?
Did you click on the page?
What browser are you using?
Do you have a custom path set?

**Comment by ongots** [comment]
Yes.
Yes. I also restarted the browser, because after updating the images did not increase.
Yes.
Firefox Beta.
No.

I reset Imagus settings and problem disappeared. Everything is working now.
