### ISSUE TITLE
Instagram, Facebook and some site won't working on Firefox

### ISSUE THREAD

**Issue by vmt1997** [TheFantasticWarrior/chrome-extension-imagus#29]
Mouse hover don't working in some site on Firefox like Instagram, Facebook or this site https://www.nogizaka46.com/s/n46/diary/detail/101617?ima=0021 only some of them work

**Comment by kuzn123** [comment]
Why did you decide that these problems are related to Imagus Mod?

**Comment by vmt1997** [comment]
because I using Imagus to zoom image and it doesn't zoom

**Comment by kuzn123** [comment]
> because I using Imagus to zoom image and it doesn't zoom

Imagus or Imagus Mod? Does everything work on the original Imagus?

**Comment by TheFantasticWarrior** [comment]
https://www.reddit.com/r/imagus/comments/14vimhp/instagram_sieve_randomly_stopped_working_only_on/

for facebook, some images work, some don't

imagus(mod) uses sieves to support sites, this github is for base code updates. for sieves/sites support visit reddit r/imagus

@kuzn123 please provide more useful info and use kind words

**Comment by kuzn123** [comment]
>> please provide more useful info and use kind words

It was initially a mistake to try to discuss with a user who is not even able to answer the simplest questions. I will try in the future not to answer at all in topics that I did not create myself.
