### ISSUE TITLE
Problem with the keyboard layout (if language not ENG)

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#3]
When using "S" (and sometimes CTRL+S) to save content, it sometimes happens that the language layout is not English. And in this case, the hotkey does not work and you have to switch the layout to English first. 

Is it possible to make two hotkeys (or two different keyboard shortcuts) per action for the content saving function? For example, Russian "Ы" and English "S" (this is one key on the keyboard)?

Or forced switching to the English layout when pressing a key - if this is possible to implement.

Imagus itself already has such functionality (two hotkeys) - but not for saving content, but for scrolling through the album and switching to full zoom mode.

**Comment by kuzn123** [comment]
By the way, I noticed that in the original extension there is no problem with the keyboard layout (language) when using CTRL+S. Regardless of which language is installed (specifically on my computer it is EN/ RU) - saving by CTRL+S occurs without problems.

In your mod, if RU language is installed, in FF opens a dialog of saving the entire page (HTML), and in Chrome - just nothing happens...

**Comment by TheFantasticWarrior** [comment]
It's because I used the event.key which treats left alt the same as right alt, and numbers above qwerty and numpad keys the same etc, and shows shorter keys instead of ControlRight etc
try [imagus_mod-0.10.7.zip](https://github.com/TheFantasticWarrior/chrome-extension-imagus/files/11195514/imagus_mod-0.10.7.zip) and see if it's fixed

**Comment by kuzn123** [comment]
I have tested it (for now a little). 
It seems to work now regardless of the current language, thanks. 

But there is one exception:
https://www.flickr.com/photos/chris_rankin/
After several downloads in a row, the mod offers to download HTML again. The same thing happens when you change the language.

**Comment by TheFantasticWarrior** [comment]
Does it still happen after you wait for the image to load? I tried 30 downloads and had no issue. 

> when you change the language. 

I installed russian keyboard still no issue, whether ru to en or en to ru no problem
