### ISSUE TITLE
0.10.14> Importing settings is triggered only once

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#32]
Starting from version 0.10.14 and higher, the import of Settings is triggered only once, immediately after installing the extension. When trying to import again, the Settings page simply "flashes" (the import window does not appear). There are no problems with exporting. Tested on Cent, CatXP, FF DE.

**Comment by TheFantasticWarrior** [comment]
Everything works fine for me, is there error message?

**Comment by kuzn123** [comment]
The console is empty. But when the screen "flashes", you can notice that the import form appears and then **closes instantly**.

I also noticed that the **Settings tab** always becomes active at the time of import.

I also noticed:
"Import Settings" 0.10.13 - this is a link (works).
"Import Settings" 0.10.14 - this is a button (not working).

I have this happening on all browsers - I tested it on 360, Edge, Chrome.

The error was [confirmed](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=2020#13) by another user.

**Comment by TheFantasticWarrior** [comment]
does it happen on fresh install? And in console can you get the value of `$("import").onclick` and `imprt_file.onchange`

**Comment by kuzn123** [comment]
> does it happen on fresh install? 

Yes. With all versions 0.10.14>

> And in console can you get the value of `$("import").onclick` and `imprt_file.onchange`

Where (how) to see it?

**Comment by TheFantasticWarrior** [comment]
In console paste and press enter

**Comment by kuzn123** [comment]
> In console paste and press enter

https://i.imgur.com/adVDa2p.png
(Chrome 114)

https://i.imgur.com/m5s3Lf0.png
(FF DE 116)


UPD
In version 0.10.14.4 importing settings **does not work at all**.

**Comment by TheFantasticWarrior** [comment]
should be fixed

**Comment by kuzn123** [comment]
Fixed. Thanks!
