### ISSUE TITLE
Automatic update address issue

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#33]
My understanding is that the address for the (semi)automatic update will no longer work:

https://i.imgur.com/B9iUf12.png
https://github.undefined.moe/wvxwxvw/Imagus_sieve_RuBoard

Accordingly, we will need a new address on Github. Can you transfer the update file to your repository and fix the address in Imagus Mod itself?

**Comment by TheFantasticWarrior** [comment]
can your repository be used? I won't know if the sieves are updated or not and I dont want to check

**Comment by 54m4d** [comment]
@kuzn123 Do you have more information about this? i tested the update with the original extension and it works fine, the rep is read only but it still works.

**Comment by kuzn123** [comment]
> can your repository be used? I won't know if the sieves are updated or not and I dont want to check

Theoretically it is possible, but I don't know Github well. How do I transfer the update file to my repository?

**Comment by TheFantasticWarrior** [comment]
If you use the GitHub website there should be an upload files button in your repository, after uploading click commit and "view raw" to get the file link

**Comment by kuzn123** [comment]
I think I got it. We need to create a file update.txt and upload it to Github, and then just edit it.

Here is the new address for automatic updates:
https://raw.githubusercontent.com/kuzn123/Imagus-Sieve-RuBoard/master/update.txt

Accordingly, we need a new version of Imagus Mod with a corrected address for updates.
