### ISSUE TITLE
Prevent update sieve button from saving changes immediately

### ISSUE THREAD

**Issue by 54m4d** [TheFantasticWarrior/chrome-extension-imagus#36]
Hi

When i click the update sieve button, the changes are saved immediately without clicking the save button, i don't know why is this behaviour?

When the update is done, one should confirm the changes by clicking the save button, this is useful in case of accidental clicks on the update sieve button.

**Comment by TheFantasticWarrior** [comment]
I thought it was convenient and prevents forgetting to save before I removed the confirm dialog, changed
