### ISSUE TITLE
Second zoom issues on Reddit

### ISSUE THREAD

**Issue by elylv** [TheFantasticWarrior/chrome-extension-imagus#4]
Having some issues with the addon in Chrome.  When I hover over an image, it will zoom as normal.  If I unhover, then hover over the same image link again, it no longer zooms or tries to zoom.  If I hover over some other link, it will display that fine first time again, but second time does not work.

Noticing this mostly on Reddit.

**Comment by kuzn123** [comment]
Do you need more detailed information - a specific link, where is this happening, the extension version, what kind of Reddit do you have - "old" or "new"? And have you already tried to solve the problem yourself: [TROUBLESHOOTING](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=9#1)?

**Comment by elylv** [comment]
v10.6.4 (happens on v10.6 also).  Happens on every image on front page of OLD reddit, just checked and it's not doing it on NEW reddit.

**Comment by kuzn123** [comment]
> v10.6.4 (happens on v10.6 also). Happens on every image on front page of OLD reddit, just checked and it's not doing it on NEW reddit.

Is everything working correctly on your original extension? 

I don't think this is a problem of this mod at all. Most likely, you have incorrectly configured sieves for the OLD Reddit. See p.20 [FAQ](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=7#1).

PS
I have now set up my Imagus mod 01064 on CentBrowser for OLD.Reddit - everything works for me. Tested it here:
https://old.reddit.com/r/all/

**Comment by elylv** [comment]
It was working on the old Imagus, but I'm unsure what I'm supposed to do based on FAQ 20... I see those 8 rules in the seive, but am I supposed to enable/disable some of them?  The colours don't match what I see in the FAQ so I'm a little confused.  The noted rules seem to be for video links rather than image, if I'm reading them correct?  Videos were always janky with old/new Imagus, so I'm more concerned with the images.

**Comment by kuzn123** [comment]
It looks like you just need to read the FAQ first (starting from the first points, especially how to enable/disable sieves). It is also unclear whether you know how to update the sieves and whether you are doing it correctly. You need to read the information from the [FAQ](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=7#1) and [SIEVES](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=5#1) sections very carefully. And also [TROUBLESHOOTING](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=9#1).

**Comment by elylv** [comment]
I had been manually updating the seives from the Imagus subreddit on the old extension.  I installed this one as I thought it was basically a patched version to pull seive updates from the ruboard source automatically (whereas the old extension is hardcoded to a non-updated source).  Do I still need to update manually?

**Comment by kuzn123** [comment]
> I had been manually updating the seives from the Imagus subreddit on the old extension. I installed this one as I thought it was basically a patched version to pull seive updates from the ruboard source automatically (whereas the old extension is hardcoded to a non-updated source). Do I still need to update manually?

From the point of view of using semi-automatic updates (using the "update sieves" button), this mod is really more convenient, since it already has the correct channel for updating configured. But otherwise there is no difference. 

It is not so important now to manually update it (from a file) or using a button in mod. It is important that this is done **correctly**. Approximately as described here:

https://www.reddit.com/r/imagus/comments/12g5zx7/comment/jfjvyed
