### ISSUE TITLE
Cannot install latest release for Firefox: "This add-on appears to be corrupt"

### ISSUE THREAD

**Issue by coredumperror** [TheFantasticWarrior/chrome-extension-imagus#43]
I tried installing the latest release for Firefox, and I got this error message:

> This add-on could not be installed because it appears to be corrupt.

Any idea what might be going on, and how to fix it? I used the "Install Add-on from File" option, selected the zip file I downloaded from the Releases page, and got that error.

I'm using Firefox Developer Edition 118.0b3.

**Comment by TheFantasticWarrior** [comment]
You can download from the add-on site, or if you want to test the new versions go to about:debugging and install temporary add-on

**Comment by coredumperror** [comment]
Ah, thanks. I didn't realize I could just install the plugin normally.
