### ISSUE TITLE
Date indicator

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#44]
Is it possible to add a rule-set **date** to IM? It can be taken, for example, from the modification date **update.txt** from [here](https://github.com/kuzn123/Imagus-Sieve-RuBoard/edit/master/update.txt
). Or somehow embed it in the file code update.txt (Imagus_sieve_RuBoard_xxxx.xx.xx_xxx.json) itself. That is, I would like each update to contain a date, a "time stamp". Probably, there is still a need to think through the concept of how to do it better.

So that the sieves can be exported/imported already with the **date indicator** and that it is displayed on the "Sieves" tab in a separate field to the right of the field with the number of sieves:

https://i.imgur.com/EOhBD1V.png

Other users have already asked me a similar question, and I also understand that in order to avoid confusion with the import of sieves, this function is really necessary for us.

**Comment by TheFantasticWarrior** [comment]
should the timestamp be changed when the user modifies anything? should exports use the timestamp or the time export button is pressed?

**Comment by kuzn123** [comment]
>should the timestamp be changed when the user modifies anything?

No. The idea was that each update of the sieves would have its own **permanent** timestamp, corresponding to the time of change **update.txt** on Github. And so that it is displayed to the right of the counter of the number of sieves.

Where to get timestamp is still a question. There are different options (and I do not know which of them can be implemented and which cannot).

- For example, you can get the timestamp from the description of the file update.txt:
https://i.imgur.com/wTyoo4W.png
https://github.com/kuzn123/Imagus-Sieve-RuBoard/commit/c7c9582e9135c844fb2dd3c3e646857dc133591d
- I can put it as a parameter? directly in update.txt when changing it (I can do this when editing update.txt)
- You can take the time of the change itself update.txt .
Etc.

>should exports use the timestamp or the time export button is pressed?

I think for a start it's worth leaving a timestamp for now, and then it will be seen.

**Comment by TheFantasticWarrior** [comment]
![2023-09-17 14-48-08](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/39485135/65787a4e-f4e7-4b25-ae0f-e03284157823)
can you add it like this?(the format of the date doesn't matter)

so just show it in the sieves menu? and add it in the file/filename on export?

**Comment by kuzn123** [comment]
> can you add it like this?(the format of the date doesn't matter)

Yes, no problem.

> so just show it in the sieves menu?

If you mean the Sieves tab in Settings, then yes.

> and add it in the file/filename on export?

Yes.

**Comment by kuzn123** [comment]
Install 0.10.15 for Chrome, the function is declared, but it works while there are the following problems:
1. There is no compatibility with the sieve format of the original Imagus (importing a sieve with the date field results in an empty sieve with the name "date").
2. When importing even one sieve, if it has a date, it is displayed instead of the rule-set date. At this point, it is the rule-set date that is needed, and not the date of any individual sieve. I think the date for individual sieves is not needed, only the date for the entire rule-set is needed (on the day of the update).
3. When importing all sieves with a date, it is displayed. But if you close the Settings and then go back to them, the date is no longer displayed.

I think the **date for each individual sieve is not needed**. You only need the update date of the rule-set (in a separate field next to the counter). Is it possible to make the "date" field activated only for a set of sieves from 500> sieves (just as an example of a verification criterion)? And for all the others (single sieves or sets of sieves) - was it either absent at all during export, or was it ignored?

**Comment by willhansen** [comment]
Not sure if it fully lines up with previous posts in this issue, but I'm interested in an option to put a current timestamp in RFC3339/ISO8601 format in filenames of all downloaded images.  Ideally configurable, but my use case would be `<date>_<original filename>`.

**Comment by kuzn123** [comment]
> Not sure if it fully lines up with previous posts in this issue, but I'm interested in an option to put a current timestamp in RFC3339/ISO8601 format in filenames of all downloaded images. Ideally configurable, but my use case would be `<date>_<original filename>`.

This does not apply to this topic, it is better to **create a separate topic**. As far as I understand, it would be better to implement this as an **option in the Settings**. Because not all users need a date in the file name.

**Comment by kuzn123** [comment]
Since the functionality with the rule-set date has not been finalized, I think it's better to remove it altogether. After all, it's not that important. What we have now only gets in the way when importing sieves.

**Comment by TheFantasticWarrior** [comment]
I think I fixed it, check latest release

**Comment by kuzn123** [comment]
> I think I fixed it, check latest release

I confirm that it has been fixed. Thanks.
