### ISSUE TITLE
"Enabled while holding ctrl" not working

### ISSUE THREAD

**Issue by SpitFire-666** [TheFantasticWarrior/chrome-extension-imagus#5]
Extension works fine in the default "Disabled while holding CTRL", but doesn't seem to work when setting like this:

![image](https://user-images.githubusercontent.com/38451588/230895238-68949890-a1bb-403c-8d47-72c382c6a01e.png)

Thanks!

**Comment by kuzn123** [comment]
You didn't specify which **browser** and extension **version** you have. It is also advisable to specify at least a few **sites** where this option does not work for you.

Does this functionality work for you in the original version of Imagus?

**Comment by SpitFire-666** [comment]
My bad, using Firefox, Imagus mod v0.10.6.4. I can't get this function to work on **any** site.

Original Imagus works - have been using it for years (with the Enabled w/Ctrl option):

![image](https://user-images.githubusercontent.com/38451588/231029593-4d2c24e5-e3f3-4355-a153-f8d58c14fc3d.png)

Imagus mod shows the dashed outline but Ctrl does not have any effect:

![image](https://user-images.githubusercontent.com/38451588/231029777-a32d47c8-e2e9-4b3c-bddb-ad68ca3b5830.png)

A couple websites:

https://www.bbc.co.uk/sounds/play/live:bbc_6music

https://www.bunnings.com.au/search/products?q=concrete+screw&sort=BoostOrder&page=3&pageSize=36

Cheers

**Comment by TheFantasticWarrior** [comment]
You have to hold control, THEN move the mouse cursor to an image, then stop the mouse, then up to you to release control or not.
Tell me if it still doesn't work. I don't think I changed this part at all though.

edit: seems like the original works even with different order, will fix

**Comment by TheFantasticWarrior** [comment]
>> https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.7.1 should be fixed


NB!
This version must be urgently removed from the releases - all files are saved (on Cent, by CTRL+S) as "undefined"...

**Comment by kuzn123** [comment]
>A couple websites:

I have on the current version (0.10.7) everything works correctly on your examples.
On version 0.10.6.4, too, everything worked correctly.

**Comment by TheFantasticWarrior** [comment]
@kuzn123 If there are unrelated issues in a new update, please open a new issue and don't reopen unless the same issue is still broken

**Comment by SpitFire-666** [comment]
Confirmed working with the new version, thankyou sir! (hope this didn't re-open the github issue)
