### ISSUE TITLE
【NSFW】同样的规则只在原版有效

### ISSUE THREAD

**Issue by loveqianool** [TheFantasticWarrior/chrome-extension-imagus#6]
同样用的 31-03-2023 的规则集
目前发现两个站点
Pixiv.net 这个站点部分失效
exhentai.org 这个站点完全失效
这两个站点都需要注册账户，不知道您那边方不方便测试

**Comment by TheFantasticWarrior** [comment]
我测试原版刚安装没问题，但用新的规则集有一样的问题，确定你用原版是新的规则集吗？
由于开发规则集的人不是我，我再问问看

**Comment by kuzn123** [comment]
It is necessary to start with the CORRECT import of new rules.

Are you sure you did everything right? It is very important to completely delete all the old sieves first, then click SAVE. Next, it is recommended (so it is more reliable) to exit the Settings altogether and go back into them, make sure that the old sieves have definitely been removed. And only after that already import new sieves. And don't forget to click SAVE after importing. 

On the [SIEVES](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=5#1) there is a GIF of how to import sieves from a file (ZIP archive) correctly.

By the way, I noticed that the mod is installed with sieves that are imported incorrectly (there is a broken order of sieves and old sieves, it seems, not completely deleted). Before any import, both from the file and through the "update sieves" button, you need to make sure that all the old sieves are exactly removed.

**Comment by kuzn123** [comment]
Unfortunately, you imported the new sieves incorrectly and added them to your mod. That is, any user of your mod now has an incorrectly imported set of sieves, which can behave completely unpredictably. The fact is that some sieves affect other sieves and it is important how they are positioned relative to each other in our rule-set. The order of arrangement is important, and in your mod it is now broken. Not only PIXIV or E-HENTAI may be broken...

**Comment by TheFantasticWarrior** [comment]
> By the way, I noticed that the mod is installed with sieves that are imported incorrectly (there is a broken order of sieves and old sieves, it seems, not completely deleted). Before any import, both from the file and through the "update sieves" button, you need to make sure that all the old sieves are exactly removed.

Weird, I thought I replaced the sieves through local file. I guess there's code in the background that messed it up
After doing it the right way e-/exhentai is still not enlarged, with ex only yellow circle so far

**Comment by loveqianool** [comment]
exhentai 我确定是使用相同规则的情况下 mod 不起作用。

**Comment by kuzn123** [comment]
E-HENTAI.ORG it is blocked in Russia and everything depends on the quality of the proxy. The sieve works, but sometimes it shows a "red indicator" (communication problems due to the proxy, as I understand it). 

PIXIV works, but there's another problem - you can't save the image to disk (status "failed" / "forbidden"). I will write about this later in a separate topic. 

I can't access on EXHENTAI.ORG even through a proxy.

**Comment by TheFantasticWarrior** [comment]
oh mb I only tested on thumbnails, if I click in albums it does work
@loveqianool 抱歉目前需要全部清除再汇入，不然会有问题，之后更新会处理这件事
正确汇入的话搜素旁会显示698而不是708

**Comment by kuzn123** [comment]
> 698而不是708

Not only the quantity must match. The order of sieves is also important. Therefore, I advise you to focus on our update file on the [SIEVES](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=5#1) page.

**Comment by TheFantasticWarrior** [comment]
> Not only the quantity must match. The order of sieves is also important. Therefore, I advise you to focus on our update file on the [SIEVES](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=5#1) page.

I know, just giving an indicator that if the number is wrong, which it will be if he imported the latest sieves without wiping, no need to let the user know every single detail
