### ISSUE TITLE
[object Object] on #sieve_date

### ISSUE THREAD

**Issue by mortyobnoxious** [TheFantasticWarrior/chrome-extension-imagus#61]
Hi, first of thank you for continuing this.

As you can see image below it says [object Object] on #sieve_date element instead of a date or something.

![firefox_D1QBQ8XJOy](https://github.com/TheFantasticWarrior/chrome-extension-imagus/assets/42044258/baa23408-55af-4912-90b7-7fecea8ea3e4)

**Comment by kuzn123** [comment]
This was fixed in 0.10.16. But in this release there is a problem with the operation of sieves.
