### ISSUE TITLE
[NSFW] Incorrect file names + download problems on some large sites

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#8]
I apologize in advance for the large number of examples, these are ALL large sites with errors that I found, on the rest (it seems) saving by hotkey (tested only the CTRL+ S combination) works correctly.

I must say right away that version 01071 contains a serious bug - all files are saved with the name "undefined", regardless of the keyboard layout.

500px
https://500px.com/editors
==
Imagus: 
v2 (EN/RU), download ok
Mod (0107):
v2.jpg (EN), download ok
v2.jpg (RU), download FAILED
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

ARTUNTAMED.COM
https://artuntamed.com/index.php?media/featured
==
Imagus:
index.php (EN/RU), download ok
Mod (0107):
index.jpg (EN/RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

DEVIANTART.COM
https://www.deviantart.com/funfictionart/gallery/all
==
Imagus:
dfr1c5b-7f337cb7-339f-4df5-9a3c-350db4e04a6b.png (EN), download ok 
dfr1c5b-7f337cb7-339f-4df5-9a3c-350db4e04a6b.png (RU), download ok
Mod (0107):
dfr1c5b-7f337cb7-339f-4df5-9a3c-350db4e04a6b.png (EN), download ok 
dfr1c5b-7f337cb7-339f-4df5-9a3c-350db4e04a6b.png (RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

DISK.YANDEX.RU
http://forum.ru-board.com/topic.cgi?forum=5&topic=48222&start=3540#4
==
Imagus: YNMFzvZPXCcqPISp2ppMmg44v55_wwUu6hXhyzlHLzXTCCchnhr5Jo6okrxVYoOJnT55oyWwc_M8EoiIAfZGXQ== (EN), download ok 
YNMFzvZPXCcqPISp2ppMmg44v55_wwUu6hXhyzlHLzXTCCchnhr5Jo6okrxVYoOJnT55oyWwc_M8EoiIAfZGXQ== (RU), download ok 
Mod (0107):  YNMFzvZPXCcqPISp2ppMmg44v55_wwUu6hXhyzlHLzXTCCchnhr5Jo6okrxVYoOJnT55oyWwc_M8EoiIAfZGXQ==.webp (EN), download ok 
YNMFzvZPXCcqPISp2ppMmg44v55_wwUu6hXhyzlHLzXTCCchnhr5Jo6okrxVYoOJnT55oyWwc_M8EoiIAfZGXQ==.webp (RU), download ok 
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

DRIVE.GOOGLE.COM
http://forum.ru-board.com/topic.cgi?forum=5&topic=48222&start=3240#16
==
Imagus:
uc (EN/RU), download ok
Mod (0107):
uc.jpg (EN/RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

GETTYIMAGES.COM
https://www.gettyimages.com/search/2/image?family=creative&phrase=ORANGE
==
Imagus: 
id900779062 (EN/RU), download ok
Mod (0107):
id900779062.jpg (EN/RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

GOO.GL
https://forum.ru-board.com/topic.cgi?forum=5&topic=48222&start=3900#7
==
Imagus:
mhdh6cGlHInsdK-dGITTA0inTu9Ew4J6WER6BOQBluYfItgr-Oc1almqT17hhvj-z5hPLvaNZnG7j0hDFGzq21B3q64quBn6YpKL8zr0Kns_l-ed1pPod8Tjsna7feskCtk9FmUO=s0 (EN/RU), download ok
Mod (0107):
mhdh6cGlHInsdK-dGITTA0inTu9Ew4J6WER6BOQBluYfItgr-Oc1almqT17hhvj-z5hPLvaNZnG7j0hDFGzq21B3q64quBn6YpKL8zr0Kns_l-ed1pPod8Tjsna7feskCtk9FmUO=s0.jpg
(EN/RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

HENTAI-MOON.COM
https://hentai-moon.com/en/
==
Imagus: 
download (EN/RU), download ok
Mod (0107):
download.mp4 (EN/RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

TIKTOK.COM
https://www.tiktok.com/@rad.miru
==
Imagus:
download (EN/RU), download ok
Mod (0107):
download.mp4 (EN), download ok
download.mp4 (RU), download FAILED
Context menu (FF):
efB6QG0r.mp4 (EN), download ok
L3xKbceR.mp4 (RU), download ok
Cent (01064):
Untitled.htm (EN/RU), download FORBIDDEN
Context menu (Cent):
Untitled.htm (EN/RU), download FORBIDDEN
("Access Denied. You don't have permission to access  "http://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/6931f508ea2746e0ab52923ddcf7bf1c/?" on this server".)
Cent (01071):
undefined (EN/RU), download ok

TUMBLR.COM
https://www.tumblr.com/tagged/painting?sort=top
==
Imagus:
06d2a51d32508ffdcab93ed91d964cf85d82690c.jpg (EN/RU), download ok
Mod (0107):
06d2a51d32508ffdcab93ed91d964cf85d82690c.jpg (EN/RU), download ok
Context menu (FF DE):
correct file name (EN/RU), download ok
Cent (01064):
correct file name, download ok (with EN layouts, RU - does not respond to hotkey)
Cent (01071):
undefined (EN/RU), download ok

YOUTUBE.COM
==
(downloads without problems, but I would like a video with the normal original title)
Imagus:
maxresdefault.jpg + videoplayback
Mod (0107):
maxresdefault.jpg + videoplayback.mp4
Context menu (FF):
maxresdefault.jpg + videoplayback.mp4
Cent (01064):
maxresdefault.jpg + videoplayback.mp4

**Comment by TheFantasticWarrior** [comment]
Sorry forgot to check downloads on chrome side, all undefined should work in https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.7.3
If it's the same issue everywhere, there's no need to provide examples

**Comment by kuzn123** [comment]
Thanks!

There is still a separate problem with saving on Pixiv (the image is not saved by CTRL+S, and also on Cent the name is incorrect).

PIXIV.NET
https://www.pixiv.net/en/tags/%E5%B0%91%E5%A5%B3/artworks#ppixiv
==
Imagus (FF):
107095985_p0.png (EN/RU), download FAILED
Mod FF (0107):
107095985_p0.png (EN/RU), download FAILED
Context menu (FF):
107095985_p0.png (EN/RU), download ok
+
Imagus (CENT):
107096291_p0.htm (EN/RU), download FAILED ("Error: Forbidden")
Mod CENT (01073):
0.htm (EN/RU), download FAILED ("Error: Forbidden")
Context menu (CENT):
107095985_p0.png (EN/RU), download ok

**Comment by TheFantasticWarrior** [comment]
https://github.com/TheFantasticWarrior/chrome-extension-imagus/issues/2#issuecomment-1502987467 

as I said here you need simple modify headers for pixiv, did you have it on?

**Comment by kuzn123** [comment]
> as I said here you need simple modify headers for pixiv, did you have it on?

Yes, I have a rule for PIXIV, SMH is enabled. The download is not happening. Maybe you have some other rule, you haven't corrected it?

**Comment by TheFantasticWarrior** [comment]
weird, I remember it working yesterday but it's not working today
anyways I don't think I am able to fix this

**Comment by kuzn123** [comment]
> weird, I remember it working yesterday but it's not working today
> anyways I don't think I am able to fix this

Ok, one site is not so important. And what about the incorrect names in the examples above on FF? Cent keeps the names mostly correct.

**Comment by TheFantasticWarrior** [comment]
I am not sure how to get the correct file name either, the only things I can access are url and captions if there are any, but those are probably worse than what the browser choose except a few sites

**Comment by kuzn123** [comment]
> I am not sure how to get the correct file name either, the only things I can access are url and captions if there are any, but those are probably worse than what the browser choose except a few sites

Ok, it was just a question. The main bug - downloading files without extensions at all has already been solved.

**Comment by kuzn123** [comment]
0.10.8

I noticed one **important difference when saving videos on TikTok** (FF, 0.10.8) - if you just try to save a popup by CTRL+S, the browser does not save it (FAILED status). But if you switch it to ZOOM mode (click RMB) and then press CTRL+S - the video is saved to disk without problems, in both layouts (EN/ RU).

Unfortunately, when saving images to PIXIV, this method does not work.

There were also problems with saving videos on TikTok on version 0.10.8 on Cent - videos are not saved at all (in downloads 0.HTM - ERROR FORBIDDEN).

**Comment by TheFantasticWarrior** [comment]
> > as I said here you need simple modify headers for pixiv, did you have it on?
> 
> Yes, I have a rule for PIXIV, SMH is enabled. The download is not happening. Maybe you have some other rule, you haven't corrected it?

after opening a tab with o, then returning to the tab to use imagus mod download works, but if I close the tab in middle of download it fails

**Comment by TheFantasticWarrior** [comment]
https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.8.1 tested tiktok and pixiv on ff, both saves without extra steps

**Comment by kuzn123** [comment]
> https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.8.1 tested tiktok and pixiv on ff, both saves without extra steps

NB! - BUG

Unfortunately, this version (0.8.10.1) does not respond to pressing hot keys at all (I tried CTRL+S / S). It seems that the browser generally does not receive commands from Imagus to download the contents of the pop-up window.

This happens on all sites, I tried it on CENT and on "pure" Ungoogled (without extensions and with standard settings).

**Comment by TheFantasticWarrior** [comment]
It seems that chromium based browsers can't use the fix (referrer download header)
I reuploaded the zip in the same version

**Comment by kuzn123** [comment]
> It seems that chromium based browsers can't use the fix (referrer download header)
> I reuploaded the zip in the same version

Everything is back to what it was on version 0.10.8 (PIXIV and TIKTOK save as 0.htm).

**Comment by TheFantasticWarrior** [comment]
try firefox downloads

**Comment by kuzn123** [comment]
> try firefox downloads

Mod FF (0.10.8)

PIXIV
107095985_p0.png (EN/RU), download FAILED
"zoom mode":
107095985_p0.png (EN/RU), download FAILED
Context menu (always "zoom mode"):
107095985_p0.png (EN/RU), download OK

When disabling the SMH rule (only needed for external links), the result is the same.


TIKTOK
1. SMH turned on:
download.mp4 (EN/RU), download FAILED

"zoom mode":
download.mp4 (EN), download OK
download.mp4 (RU), download FAILED

Context menu (always "zoom mode"):
hUS6CyK8.mp4 (EN), download OK
n1kATiGN.mp4 (RU), download OK

2. SMH turned off:
download.mp4 (EN/RU), download OK (80%) / download FAILED (20%)
(moreover, the names of some videos differ from "download.mp4")

"zoom mode":
download.mp4 (EN), download OK (80%) / download FAILED (20%)
download.mp4 (RU), download OK (80%) / download FAILED (20%)

Context menu (always "zoom mode"):
hUS6CyK8.mp4 (EN), download OK
n1kATiGN.mp4 (RU), download OK

It seems that with the disabled SMH (rule for TikTok it is only needed for the sieve to work on external links and on other sites), everything is getting much better. I wrote about it in a note to the sieve.

**Comment by TheFantasticWarrior** [comment]
0.10.8.1

https://user-images.githubusercontent.com/39485135/231730096-23d5f518-b83c-4634-ac46-145423dbbb17.mp4
