### ISSUE TITLE
Hotkey for the "wrap caption" do not work on YouTube

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#9]
The hotkeys for the "wrap caption" function do not work specifically on YouTube. Changing to a different letter or combination does not give a result.

FF (0107) / Cent (01064).

**Comment by TheFantasticWarrior** [comment]
should be fixed in 0.10.8 too

**Comment by kuzn123** [comment]
I can confirm that in version 0.10.8 (FF/CENT) the problem with wrap and hide caption by hotkey solved.
